version: '3'
networks:
  node-express-graphql-template_node-express-graphql-template_default:
    external: true
services:
  app:
    networks:
      - node-express-graphql-template_node-express-graphql-template_default
    build:
      context: .
      args:
        ENVIRONMENT_NAME: .docker
        BUILD_NAME: docker
        PLATFORM: amd64
        APP_PATH: ${APP_PATH}
    restart: always
    ports:
      - 9000:9000
    environment:
      ENABLE_DEDUP: "false"
    env_file:
      - ./.env.docker
    volumes:
      - ${APP_PATH}/dedupData.yaml:${APP_PATH}/dedupData.yaml
    stop_grace_period: 50s
